[project]
name = "rescathena.github.io"
version = "0.1.0"
description = "The rescathena documentation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material>=9.6.17",
]
